# Generated by Django 4.0.5 on 2022-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateuruser',
            name='numero',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='donateuruser',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='effectuerdonnature',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Image'),
        ),
    ]
