# Generated by Django 4.0.5 on 2022-08-15 22:41

from django.db import migrations, models
import utilisateur.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_alter_donateuruser_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectuerdonnature',
            name='photo',
            field=models.ImageField(blank=True, upload_to=utilisateur.models.EffectuerDonNature.nameFile),
        ),
    ]
